{"name": "test_02", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'data'", "trace": "self = <test_request.Test_case object at 0x0000021D66CE7470>\nconn_qianhouzhi = None\n\n    def test_02(self,conn_qianhouzhi):\n        url = \"http://172.16.0.181:8508/pwrApi/infoscreen/pdeScreen/list\"\n        data = {\n            \"projectId\":\"2c92808e80f408230180f4a9e28d04c8\"\n        }\n        header = {\n            \"userToken\":\"3d42dfd2540171e3908fc9ba8d7291a6\",\n            \"Content-Type\":\"application/json; charset=UTF-8\"\n        }\n        rep02 = requests.get(url,data,headers = header)\n        print(rep02.text)\n        #正则表达式提取\n        Test_case.tiqu = re.search('\"oid\":\"(.*?)\"',rep02.text)[1]\n        print(Test_case.tiqu)\n        print(\"我是\"+Test_case.tiqu+\"的\")\n        print(rep02.json())\n>       YamlUtil.write_extract_yaml({\"tiqu\":rep02.json().data[1].oid})\nE       AttributeError: 'dict' object has no attribute 'data'\n\ntestcases\\test_request.py:49: AttributeError"}, "start": 1653621877316, "stop": 1653621877418, "uuid": "d52814e3-b09a-45b8-9a45-13efc54d04ac", "historyId": "4d0a09f709ef7c26a84fbb17c6036076", "testCaseId": "57f246f05d1c599e5949f24a9728ed65", "fullName": "testcases.test_request.Test_case#test_02", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_request"}, {"name": "subSuite", "value": "Test_case"}, {"name": "host", "value": "weiqiangchen"}, {"name": "thread", "value": "5344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_request"}]}